name: seqavatar
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=12.1
  - python=3.9
  - pip=25.1
  - pytorch=2.1.2
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - pip:
      - git+https://github.com/facebookresearch/pytorch3d.git
      - https://github.com/unlimblue/KNN_CUDA/releases/download/0.2/KNN_CUDA-0.2-py3-none-any.whl
      - plyfile==0.8.1
      - imageio==2.37.0
      - lpips==0.1.4
      - numpy==1.23.5
      - opencv-python==4.11.0.86
      - tensorboard==2.14.0
      - h5py==3.14.0
      - chumpy==0.70
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn